# Generated by Django 5.2 on 2025-08-16 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_episode', models.IntegerField(default=0)),
                ('policy_weights', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('states', models.TextField()),
                ('actions', models.TextField()),
                ('rewards', models.TextField()),
                ('total_reward', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project5.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='HumanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_trajectory', models.IntegerField(choices=[(1, 'Trajectory 1'), (2, 'Trajectory 2')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project5.gamesession')),
                ('trajectory1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_as_first', to='project5.trajectory')),
                ('trajectory2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_as_second', to='project5.trajectory')),
            ],
        ),
    ]
